# Generated by Django 3.1.4 on 2021-05-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_requestreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentWaitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentWaitTime', models.IntegerField(default=160)),
            ],
        ),
    ]
